var  quotes = [
'abase: cause to feel shame',
'abate:  become less in amount or intensity',
'aberration: a state or condition markedly different from the norm',
'abhor:  find repugnant',
'abject: of the most contemptible kind',
'abjure: formally reject or disavow a formerly held belief',
'abnegate: deny or renounce',
'abnegation: the denial and rejection of a doctrine or belief',
'abominable: unequivocally detestable',
'abortive:  failing to accomplish an intended result',
'abrogate: revoke formally',
'abscond: run away, often taking something or somebody along',
'absolve:  grant remission of a sin to',
'abstruse: difficult to penetrate',
'abyss: a bottomless gulf or pit',
'accede: yield to another\'s wish or opinion',
'accolade:  a tangible symbol signifying approval or distinction',
'accost: speak to someone',
'accretion: an increase by natural growth or addition',
'acquiesce: to agree or express agreement',
'acrid:  strong and sharp, as a taste',
'acumen: shrewdness shown by keen insight',
'adage:  a condensed but memorable saying embodying an important fact',
'adamant:  very hard native crystalline carbon valued as a gem',
'adamant: impervious to pleas, persuasion, requests, reason',
'address:  the place where a person or organization can be found',
'adherent:  someone who believes and helps to spread a doctrine',
'admonish: scold or reprimand; take to task',
'admonition: a firm rebuke',
'adumbrate: describe roughly or give the main points or summary of',
'adverse: in an opposing direction',
'advocate: a person who pleads for a person, cause, or idea',
'affectation:  a deliberate pretense or exaggerated display',
'affluent: having an abundant supply of money or possessions of value',
'aggrandize: add details to',
'agnostic:  a person who claims the existence of God is unknowable',
'agrarian:  relating to rural matters',
'alacrity: liveliness and eagerness',
'alias: a name that has been assumed temporarily',
'allege:  report or maintain',
'allot: give out',
'allusion:  passing reference or indirect mention',
'aloof:  remote in manner',
'ambiguous:  having more than one possible meaning',
'ambivalent: uncertain or unable to decide about what course to follow',
'ameliorate: to make better',
'amenable: disposed or willing to comply',
'amenity:  pleasantness resulting from agreeable conditions',
'amiable: diffusing warmth and friendliness',
'amity: a state of friendship and cordiality',
'amnesty:  a warrant granting release from punishment for an offense',
'amorous:  inclined toward or displaying love',
'amorphous: having no definite form or distinct shape',
'anachronistic: chronologically misplaced',
'anathema: a formal ecclesiastical curse accompanied by excommunication',
'annex: attach to',
'antediluvian: of or relating to the period before the biblical flood',
'antiseptic: thoroughly clean and free of disease-causing organisms',
'antithesis: exact opposite',
'apartheid:  a social policy of racial segregation',
'apathetic: showing little or no emotion or animation',
'aphorism:  a short pithy instructive saying',
'apocryphal: being of questionable authenticity',
'appease: make peace with',
'apprehensive: in fear or dread of possible evil or harm',
'approbation: official approval',
'aptitude:  inherent ability',
'arbiter: someone chosen to judge and decide a disputed issue',
'arbitrary: based on or subject to individual discretion or preference',
'arboreal: of or relating to or formed by trees',
'arcane: requiring secret or mysterious knowledge',
'archetypal: of an original type after which other things are patterned',
'archetype:  something that serves as a model',
'arouse: engage in boisterous, drunken merrymaking',
'arrogate: seize and take control without authority',
'ascetic: someone who practices self denial as a spiritual discipline',
'aspersion: a disparaging remark',
'assiduous: marked by care and persistent effort',
'astute:  marked by practical hardheaded intelligence',
'atrophy: a decrease in size of an organ caused by disease or disuse',
'attrition:  the act of rubbing together',
'austere:  of a stern or strict bearing or demeanor',
'avarice: reprehensible acquisitiveness; insatiable desire for wealth',
'avow:  to declare or affirm solemnly and formally as true',
'awry:  turned or twisted to one side',
'backpedal: reverse or retreat from one\'s position on an issue',
'bane: something causing misery or death',
'bashful: self-consciously timid',
'bawdy: humorously vulgar',
'beget:  generate children',
'beguile: influence by slyness',
'belabor:  beat soundly',
'beleaguer:  annoy persistently',
'belie: be in contradiction with',
'bequest:  a gift of personal property by will',
'bereavement: state of sorrow over the death or departure of a loved one',
'bereft: sorrowful through loss or deprivation',
'beset:  assail or attack on all sides',
'bilk: cheat somebody out of what is due, especially money',
'blandishment: flattery intended to persuade',
'blatant:  without any attempt at concealment; completely obvious',
'blight:  any plant disease resulting in withering without rotting',
'blithe: carefree and happy and lighthearted',
'bombastic: ostentatiously lofty in style',
'brazen: unrestrained by convention or propriety',
'brusque: marked by rude or peremptory shortness',
'buffoon: a person who amuses others by ridiculous behavior',
'burlesque: a theatrical entertainment of broad and earthy humor',
'cadence:  the accent in a metrical foot of verse',
'cajole: influence or urge by gentle urging, caressing, or flattering',
'callous: emotionally hardened',
'callow: young and inexperienced',
'calumny: a false accusation of an offense',
'camaraderie: the quality of affording easy familiarity and sociability',
'candor: the quality of being honest and straightforward',
'cantankerous: stubbornly obstructive and unwilling to cooperate',
'capitulate: surrender under agreed conditions',
'cataclysmic severely destructive',
'catharsis:  purging the body to stimulate evacuation of the bowels',
'caucus: meet to select a candidate or promote a policy',
'cavort play boisterously',
'celibacy:  abstaining from sexual relations',
'chagrin:  strong feelings of embarrassment',
'charlatan:  a flamboyant deceiver',
'chide: censure severely or angrily',
'choleric:  characterized by anger',
'circumlocution: an indirect way of expressing something',
'circumscribe: draw a geometric figure around another figure',
'circumspect: heedful of potential consequences',
'circumvent: surround so as to force to give up',
'clamor: utter or proclaim insistently and noisily',
'clandestine:  conducted with or marked by hidden aims or methods',
'clemency:  leniency and compassion shown toward offenders',
'clique:  an exclusive circle of people with a common purpose',
'coalesce:  fuse or cause to come together',
'cobbler :a person who makes or repairs shoes',
'coerce: to cause to do through pressure or necessity',
'cogent: powerfully persuasive',
'cognizant: having or showing knowledge or understanding or realization',
'coherent: marked by an orderly and consistent relation of parts',
'collectively: in conjunction with; combined',
'collusion:  secret agreement',
'commensurate: corresponding in size or degree or extent',
'commiseration: feeling of sympathy and sorrow for the misfortunes of others',
'complacency: the feeling you have when you are satisfied with yourself',
'complement: something added to embellish or make perfect',
'complicity: guilt as a confederate in a crime or offense',
'compunction: a feeling of deep regret, usually for some misdeed',
'conciliatory:  making or willing to make concessions',
'concoct: make something by mixing',
'concomitant: following or accompanying as a consequence',
'conduit: a passage through which water or electric wires can pass',
'confidant: someone to whom private matters are told',
'conflagration: a very intense and uncontrolled fire',
'congruity: the quality of agreeing; being suitable and appropriate',
'conjecture: to believe especially on uncertain or tentative grounds',
'conjure summon into action or bring into existence',
'conjure: summon into action or bring into existence',
'connive form intrigues (for) in an underhand manner',
'connive: form intrigues (for) in an underhand manner',
'connoisseur:  an expert able to appreciate a field',
'conscientious: characterized by extreme care and great effort',
'consign: give over to another for care or safekeeping',
'constituent: one of the individual parts making up a composite entity',
'construe: make sense of; assign a meaning to',
'contentious: showing an inclination to disagree',
'contiguous:  having a common boundary or edge',
'contingent: determined by conditions or circumstances that follow',
'contraband: distributed or sold illicitly',
'contravene: go against, as of rules and laws',
'contrite: feeling or expressing pain or sorrow for sins or offenses',
'contrived:  showing effects of planning or manipulation',
'contusion: an injury in which the skin is not broken',
'conundrum: a difficult problem',
'convivial: occupied with or fond of the pleasures of good company',
'corpulence: the property of excessive fatness',
'corroborate give evidence for',
'corroborate:  give evidence for',
'corroborate: give evidence for',
'coup:  a sudden and decisive change of government by force',
'covenant:  an agreement between God and his people',
'covet: wish, long, or crave for',
'cumulative: increasing by successive addition',
'cupidity: extreme greed for material wealth',
'cynic:  someone who is critical of the motives of others',
'dearth: an insufficient quantity or number',
'debacle: a sudden and violent collapse',
'debase: corrupt morally or by intemperance or sensuality',
'debauch: a wild gathering involving excessive drinking',
'debunk: expose while ridiculing',
'decadent: marked by excessive self-indulgence and moral decay',
'decimate:  kill one in every ten, as of mutineers in Roman armies',
'decry express strong disapproval of',
'decry: express strong disapproval of',
'deferential: showing courteous regard for people\'s feelings',
'definitive:  clearly formulated',
'defunct: no longer in force or use; inactive',
'delinquent: a young offender',
'deluge: a heavy rain',
'demagogue: a leader who seeks support by appealing to popular passions',
'demarche: a move or step or maneuver in political or diplomatic affairs',
'demented: affected with madness or insanity',
'demure: affectedly shy especially in a playful or provocative way',
'denigrate: charge falsely or with malicious intent',
'denounce: speak out against',
'deposition: the act of putting something somewhere',
'deprave corrupt morally or by intemperance or sensuality',
'depravity: moral perversion; impairment of virtue and moral principles',
'deride: treat or speak of with contempt',
'derivative: a compound obtained from another compound',
'despondent:  without or almost without hope',
'despot: a cruel and oppressive dictator',
'detractor: one who disparages or belittles the worth of something',
'deviant: a person whose behavior deviates from what is acceptable',
'diaphanous: so thin as to transmit light',
'dictum:  an authoritative declaration',
'didactic: instructive, especially excessively',
'diffusion: the act of dispersing something',
'diligent: quietly and steadily persevering in detail or exactness',
'dirge: a song or hymn of mourning as a memorial to a dead person',
'disaffected: discontented as toward authority',
'disavow: refuse to acknowledge',
'discern:  detect with the senses',
'discomfit: cause to lose one\'s composure',
'discourse: an extended communication dealing with some particular topic',
'disdain: lack of respect accompanied by a feeling of intense dislike',
'disillusioned: freed from false ideas',
'dismal: causing dejection',
'dismissal: the sending away of someone',
'disparage: express a negative opinion of',
'disparaging: expressive of low opinion',
'disparate: fundamentally different or distinct in quality or kind',
'dispel: to cause to separate and go in different directions',
'disrepute: the state of being held in low esteem',
'dissemination: the act of dispersing or diffusing something',
'distressed: feeling general unhappiness',
'divisive: dissenting with the majority opinion',
'dogmatic: pertaining to a code of beliefs accepted as authoritative',
'dour: showing a brooding ill humor',
'duplicity: acting in bad faith',
'duress: compulsory force or threat',
'ebullient: joyously unrestrained',
'eclectic: selecting what seems best of various styles or ideas',
'edict: a formal or authoritative proclamation',
'edify:  make understand',
'efface:  remove by or as if by rubbing or erasing',
'effigy: a representation of a person',
'effulgent: radiating or as if radiating light',
'effusion:  an unrestrained expression of emotion',
'egalitarian:  favoring social equality',
'egregious: conspicuously and outrageously bad or reprehensible',
'elated: exultantly proud and joyful; in high spirits',
'elegy: a mournful poem; a lament for the dead',
'elicit: call forth, as an emotion, feeling, or response',
'elongate: make long or longer by pulling and stretching',
'eloquent: expressing yourself readily, clearly, effectively',
'embezzle: appropriate fraudulently to one\'s own use',
'embezzlement: the fraudulent appropriation of funds or property',
'emend: make corrections to',
'emollient: a substance with a soothing effect when applied to the skin',
'empathy: understanding and entering into another\'s feelings',
'empirical: derived from experiment and observation rather than theory',
'emulate: strive to equal or match, especially by imitating',
'enervate: weaken mentally or morally',
'enfranchise: grant freedom to, as from slavery or servitude',
'engender: call forth',
'enmity: a state of deep-seated ill-will',
'ensue: issue or terminate in a specified way',
'entourage: the group following and attending to some important person',
'entrenched: dug in',
'ephemeral: anything short-lived, as an insect that lives only for a day',
'epistolary: written in the form of letters or correspondence',
'equanimity: steadiness of mind under stress',
'equitable:  fair to all parties as dictated by reason and conscience',
'equivocal: open to two or more interpretations',
'erudite: having or showing profound knowledge',
'esoteric: understandable only by an enlightened inner circle',
'espouse: choose and follow a theory, idea, policy, etc.',
'evanescent: tending to vanish like vapor',
'evince: give expression to',
'exacerbate: make worse',
'exacting:  severe and unremitting in making demands',
'exalt:  praise, glorify, or honor',
'execrable: unequivocally detestable',
'exegesis: an explanation or critical interpretation',
'exemplify:  be characteristic of',
'exhort: spur on or encourage especially by cheers and shouts',
'exigent: demanding immediate attention',
'expedient: appropriate to a purpose',
'expiate: make amends for',
'expunge: remove by erasing or crossing out or as if by drawing a line',
'expurgate: edit by omitting or modifying parts considered indelicate',
'extant: still in existence; not extinct or destroyed or lost',
'extol: praise, glorify, or honor',
'extraneous: not belonging to that in which it is contained',
'exult:  feel extreme happiness or elation',
'fabricate: make up something artificial or untrue',
'facade: the front of a building',
'facile:  arrived at without due care or effort; lacking depth',
'fallacious: containing or based on incorrect reasoning',
'farcical:  broadly or extravagantly humorous',
'farfetched: highly imaginative but unlikely',
'fatuous: devoid of intelligence',
'fecund:  capable of producing offspring or vegetation',
'feigned: not genuine',
'fetter: a shackle for the ankles or feet',
'finicky: exacting especially about details',
'flabbergasted: as if struck dumb with astonishment and surprise',
'flagrant: conspicuously and outrageously bad or reprehensible',
'flatulence: a state of excessive gas in the alimentary canal',
'flophouse: a cheap lodging house',
'flout:  treat with contemptuous disregard',
'foible:  a minor weakness or peculiarity in someone\'s character',
'foil: hinder or prevent, as an effort, plan, or desire',
'folly: the trait of acting stupidly or rashly',
'foment:  try to stir up',
'forbearance: good-natured tolerance of delay or incompetence',
'forsake: leave someone who needs or counts on you; leave in the lurch',
'forthwith: without delay or hesitation; with no time intervening',
'fortuitous: occurring by happy chance',
'fractious: easily irritated or annoyed',
'furtive: secret and sly or sordid',
'futility: uselessness as a consequence of having no practical result',
'garrulous: full of trivial conversation',
'genteel:  marked by refinement in taste and manners',
'glut:  supply with an excess of',
'gluttony: habitual eating to excess',
'gourmand: a person who is devoted to eating and drinking to excess',
'grace: elegance and beauty of movement or expression',
'grandiloquent: lofty in style',
'gratuitous: unnecessary and unwarranted',
'hapless: unfortunate and deserving pity',
'haughty: having or showing arrogant superiority',
'hegemony: the dominance or leadership of one social group over others',
'heterogenous: consisting of elements that are not of the same kind',
'hiatus:  an interruption in the intensity or amount of something',
'histrionic:  characteristic of acting or a stage performance',
'homebody: a person who seldom goes anywhere',
'hoodwink: conceal one\'s true motives from',
'hypochondriac a patient with imaginary symptoms and ailments',
'hypochondriac: a patient with imaginary symptoms and ailments',
'hypocrisy: pretending to have qualities or beliefs that you do not have',
'iconoclast: someone who attacks cherished ideas or institutions',
'idiosyncrasy:  a behavioral attribute peculiar to an individual',
'idiosyncratic: peculiar to the individual',
'idyllic:  charmingly simple and serene',
'ignominy:  a state of dishonor',
'impasse: a situation in which no progress can be made',
'impassioned: characterized by intense emotion',
'impeccable: without fault or error',
'impecunious: not having enough money to pay for necessities',
'impertinent: improperly forward or bold',
'impetuous: characterized by undue haste and lack of thought',
'impinge: infringe upon',
'impromptu: with little or no preparation or forethought',
'impudent: improperly forward or bold',
'impute: attribute or credit to',
'inadvertently: without knowledge or intention',
'inane: devoid of intelligence',
'incarnation: act of attributing human characteristics to abstract ideas',
'incense:  make furious',
'incessant:  uninterrupted in time and indefinitely long continuing',
'inchoate: only partly in existence; imperfectly formed',
'incisive:  demonstrating ability to recognize or draw fine distinctions',
'inconsequential: lacking worth or importance',
'inconspicuously: in a manner intended to avoid attracting attention',
'incontrovertible: impossible to deny or disprove',
'incumbent: necessary as a duty or responsibility; morally binding',
'indelible: cannot be removed or erased',
'indignant: angered at something unjust or wrong',
'indoctrinate: teach uncritically',
'indolent: disinclined to work or exertion',
'indulge: yield to; give satisfaction to',
'indulgent: given to yielding to the wishes of someone',
'ineffable: defying expression or description',
'inept: generally incompetent and ineffectual',
'inexorable: not to be placated or appeased or moved by entreaty',
'infamy: a state of extreme dishonor',
'inhibit: limit the range or extent of',
'inimical: not friendly',
'injunction: a judicial remedy to prohibit a party from doing something',
'innate: present at birth but not necessarily hereditary',
'inoculate: inject or treat with the germ of a disease to render immune',
'inordinate:  beyond normal limits',
'insatiable: impossible to satisfy',
'insidious: working or spreading in a hidden and usually injurious way',
'insinuation: an indirect (and usually malicious) implication',
'insipid:  lacking interest or significance or impact',
'insolent:  marked by casual disrespect',
'instigate: provoke or stir up',
'insular: narrowly restricted in outlook or scope',
'insurgent: in opposition to a civil authority or government',
'interlocutor: a person who takes part in a conversation',
'intimation: a slight suggestion or vague understanding',
'intransigent: impervious to pleas, persuasion, requests, or reason',
'intrepid: invulnerable to fear or intimidation',
'inure: cause to accept or become hardened to',
'invective: abusive language used to express blame or censure',
'inveterate: habitual',
'invigorate give life or energy to',
'irreverence: a mental attitude showing lack of due respect',
'jock: a person trained to compete in sports',
'kindred: group of people related by blood or marriage',
'knell: the sound of a bell rung slowly to announce a death',
'laconic: brief and to the point',
'lampoon:  ridicule with satire',
'largesse: liberality in bestowing gifts',
'legerdemain: an illusory feat',
'lewd: suggestive of or tending to moral looseness',
'libertarian: an advocate of freedom of thought and speech',
'licentious: lacking moral discipline',
'linchpin: a central cohesive source of support and stability',
'litigant: (law) a party to a lawsuit; someone involved in litigation',
'lugubrious:  excessively mournful',
'maelstrom: a powerful circular current of water',
'malaise:  a general feeling of discomfort, uneasiness, or depression',
'malfeasance: wrongful conduct by a public official',
'manifest:  clearly revealed to the mind or the senses or judgment',
'matriculate:  enroll as a student',
'maudlin: effusively or insincerely emotional',
'maverick: someone who exhibits independence in thought and action',
'mawkish: effusively or insincerely emotional',
'maxim: a saying that is widely accepted on its own merits',
'mellifluous:  pleasing to the ear',
'mendacious: given to lying',
'mercenary:  a person hired to fight for another country than their own',
'milieu:  the environmental condition',
'mishap: an unpredictable outcome that is unfortunate',
'modicum: a small or moderate or token amount',
'morass: a soft wet area of low-lying land that sinks underfoot',
'mores: the conventions embodying the fundamental values of a group',
'mortify: cause to feel shame',
'multifarious: having many aspects',
'munificent: very generous',
'nadir: the lowest point of anything',
'naivety: lack of sophistication or worldliness',
'nebulous:  lacking definite form or limits',
'nefarious:  extremely wicked',
'negligent: characterized by undue lack of attention or concern',
'neophyte: any new participant in some activity',
'nepotism: favoritism shown to relatives or friends by those in power',
'noisome: offensively malodorous',
'nonsensical: having no intelligible meaning',
'noxious: injurious to physical or mental health',
'obdurate: stubbornly persistent in wrongdoing',
'obfuscate: make obscure or unclear',
'oblivion:  the state of being disregarded or forgotten',
'obstreperous: noisily and stubbornly defiant',
'officious: intrusive in a meddling or offensive manner',
'omniscient: infinitely wise',
'onerous: not easily borne; wearing',
'ostensible: appearing as such but not necessarily so',
'ostentatious:  intended to attract notice and impress others',
'ostracism: the act of excluding someone from society by general consent',
'palliate: lessen or to try to lessen the seriousness or extent of',
'palpable: capable of being perceived',
'paltry:  contemptibly small in amount',
'panacea: hypothetical remedy for all ills or diseases',
'pantomime: a performance using gestures and movements without words',
'paradigm: a standard or typical example',
'pariah: a person who is rejected from society or home',
'parlance: a manner of speaking natural to a language\'s native speakers',
'partisan: a fervent and even militant proponent of something',
'paucity: an insufficient quantity or number',
'pecuniary: relating to or involving money',
'pejorative: expressing disapproval',
'pellucid: transparently clear; easily understandable',
'penance: voluntary self-punishment in order to atone for something',
'penchant: a strong liking',
'penurious: excessively unwilling to spend',
'peremptory:  putting an end to all debate or action',
'perennial: lasting an indefinitely long time',
'perfidy:  an act of deliberate betrayal',
'peripatetic:  traveling especially on foot',
'perjury:  criminal offense of making false statements under oath',
'pernicious: exceedingly harmful',
'perpetrate: perform an act, usually with a negative connotation',
'perpetually: everlastingly; for all time',
'perquisite:  an incidental benefit for certain types of employment',
'pert: characterized by a lightly exuberant quality',
'pertinacious: stubbornly unyielding',
'pertinent:  being of striking appropriateness',
'pervade:  spread or diffuse through',
'philanthropic: of or relating to charitable giving',
'philistine:  a person who is uninterested in intellectual pursuits',
'phlegmatic: showing little emotion',
'pinnacle: a slender upright spire at the top of a buttress of tower',
'pithy: concise and full of meaning',
'platitude: a trite or obvious remark',
'plaudit: enthusiastic approval',
'plenitude: a full supply',
'plethora: extreme excess',
'poignant:  keenly distressing to the mind or feelings',
'portent: a sign of something about to happen',
'potentate: a ruler who is unconstrained by law',
'precarious: not secure; beset with difficulties',
'precept:  rule of personal conduct',
'precipitous:  extremely steep',
'preclude: make impossible, especially beforehand',
'predilection: a predisposition in favor of something',
'preeminent: greatest in importance or degree or significance',
'preponderance: exceeding in heaviness; having greater weight',
'prerogative:  a right reserved exclusively by a person or group',
'presage: a foreboding about what is about to happen',
'pretentious: creating an appearance of importance or distinction',
'probity: complete and confirmed integrity',
'proclivity: a natural inclination',
'profess: confess one\'s faith in, or allegiance to',
'profligate: unrestrained by convention or morality',
'proletariat:  a social class comprising those who do manual labor',
'prominent: conspicuous in position or importance',
'promulgate: state or announce',
'prophylactic: preventing or contributing to the prevention of disease',
'proponent: a person who pleads for a cause or propounds an idea',
'proscribe: command against',
'proselytize:  convert or try to convert someone to another religion',
'protagonist: the principal character in a work of fiction',
'protean: taking on different forms',
'prurient: characterized by lust',
'puerile: displaying or suggesting a lack of maturity',
'pugnacious: tough and callous by virtue of experience',
'pulchritude: physical beauty, especially of a woman',
'punctilious: marked by precise accordance with details',
'purport:  have the often specious appearance of being or intending',
'putative:  purported',
'quaint: attractively old-fashioned',
'quandary: state of uncertainty in a choice between unfavorable options',
'quibble: evade the truth of a point by raising irrelevant objections',
'quixotic: not sensible about practical matters',
'rambunctious: noisy and lacking in restraint or discipline',
'rapacious:  living by preying on other animals',
'rebuke: an act or expression of criticism and censure',
'recalcitrance: the trait of being unmanageable',
'recluse: one who lives in solitude',
'reclusive: withdrawn from society; seeking solitude',
'recuse:disqualify oneself as a judge in a particular case',
'redolent: having a strong pleasant odor',
'redoubtable: inspiring fear',
'reek: give off smoke, fumes, warm vapour, steam, etc.',
'relegate: assign to a lower position',
'remiss: failing in what duty requires',
'renounce:  turn away from; give up',
'reprehension:  an act or expression of criticism and censure',
'reprieve: postpone the punishment of a convicted criminal',
'reprobate: a person without moral scruples',
'repudiate: refuse to acknowledge, ratify, or recognize as valid',
'requisition: an authoritative request or demand',
'rescind: cancel officially',
'respite: a pause from doing something',
'restitution: the act of restoring something to its original state',
'rhetorical: relating to using language effectively',
'ricochet: spring back; spring away from an impact',
'rife: excessively abundant',
'rift: a narrow fissure in rock',
'rudimentary:  being in the earliest stages of development',
'ruminate:  reflect deeply on a subject',
'saccharine:  overly sweet',
'sacrilege:  blasphemous behavior',
'sanctimonious: excessively or hypocritically pious',
'sanguine: confidently optimistic and cheerful',
'scion: a descendent or heir',
'scrupulous: characterized by extreme care and great effort',
'scurrilous: expressing offensive reproach',
'sectarian: of or relating to a subdivision of a larger religious group',
'semaphore: an apparatus for visual signaling',
'sequester:  keep away from others',
'serendipity: good luck in making unexpected and fortunate discoveries',
'simpleton: a person lacking intelligence or common sense',
'sloth:  a disinclination to work or exert yourself',
'sobriety: the state of being sober and not intoxicated by alcohol',
'solicitous: full of anxiety and concern',
'solidarity: a union of interests or purposes among members of a group',
'solipsism: the philosophical theory that the self is all that exists',
'solitary: not growing or living in groups or colonies',
'spurious: plausible but false',
'staid: characterized by dignity and propriety',
'steadfast: marked by firm determination or resolution; not shakable',
'stern: of a strict bearing or demeanor; forbidding in aspect',
'stolid: having or revealing little emotion or sensibility',
'strident: unpleasantly loud and harsh',
'strife:  bitter conflict; heated often violent dissension',
'subjugate: make subservient; force to submit or subdue',
'subversive:  in opposition to an established system or government',
'succinct:  briefly giving the gist of something',
'supercilious:  having or showing arrogant superiority to',
'surfeit: indulge (one\'s appetite) to satiety',
'surreptitious: marked by quiet and caution and secrecy',
'sustain: lengthen or extend in duration or space',
'swarthy: naturally having skin of a dark color',
'swindle: deprive of by deceit',
'sycophant: a person who tries to please someone to gain an advantage',
'taciturn: habitually reserved and uncommunicative',
'tangential: of superficial relevance if any',
'tantamount:  being essentially equal to something',
'tart up: dress up in a cheap and provocative way',
'teetotaler: a total abstainer',
'temerity:  fearless daring',
'tenable:  based on sound reasoning or evidence',
'tenacious:  stubbornly unyielding',
'tentative: hesitant or lacking confidence; unsettled in mind or opinion',
'tenuous:  very thin in gauge or diameter',
'thrifty: mindful of the future in spending money',
'tirade: a speech of violent denunciation',
'toady: a person who tries to please someone to gain an advantage',
'tome: a large and scholarly book',
'torpid: in a condition of biological rest or suspended animation',
'transcend: go beyond the scope or limits of',
'transgress:  act in disregard of laws, rules, contracts, or promises',
'transient:  lasting a very short time',
'travesty: a composition that imitates or misrepresents a style',
'trenchant: having keenness and forcefulness and penetration in thought',
'trepidation:  a feeling of alarm or dread',
'tripe: lining of the stomach of a cow (used as food)',
'trite: repeated too often; overfamiliar through overuse',
'trope: language used in a figurative or nonliteral sense',
'truculent: defiantly aggressive',
'turpitude: a corrupt or depraved or degenerate act or practice',
'tutelage: attention and management implying responsibility for safety',
'ubiquitous: being present everywhere at once',
'umbrage: a feeling of anger caused by being offended',
'unctuous:  unpleasantly and excessively suave or ingratiating',
'unremitting:  uninterrupted in time and indefinitely long continuing',
'unwitting:  not aware or knowing',
'upbraid: express criticism towards',
'utilitarian: having a useful function',
'venal:  capable of being corrupted',
'veracity: unwillingness to tell lies',
'verisimilitude:  the appearance of truth; the quality of seeming to be true',
'vestige: an indication that something has been present',
'vial: a small bottle that contains a drug',
'vicarious:  experienced at secondhand',
'vicissitude: a variation in circumstances or fortune',
'vile: morally reprehensible',
'vilify:  spread negative information about',
'virtuoso: someone who is dazzlingly skilled in any field',
'vitiate:  make imperfect',
'vitriolic: harsh, bitter, or malicious in tone',
'vituperate: spread negative information about',
'vociferous: conspicuously and offensively loud',
'volition: the act of making a choice',
'wanton: a lewd or lascivious person',
'waver: pause or hold back in uncertainty or unwillingness',
'willful:  done by design',
'wily: marked by skill in deception',
'winsome: charming in a childlike or naive way',
'wistful: showing pensive sadness',
'yoke: join with stable gear, as two draft animals',
'zephyr: a slight wind'
]

function newQuote() {
    var randomNumber = Math.floor(Math.random() * (quotes.length));
document.getElementById("quoteDisplay").innerHTML = quotes[randomNumber];
}

newQuote();

